export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_RESULT = 'LOGIN_RESULT';
export const LOGOUT_RESULT = 'LOGOUT_RESULT';
export const OPEN_WELCOME_SUCCESS = 'OPEN_WELCOME_SUCCESS';
export const CLOSE_WELCOME_SUCCESS = 'CLOSE_WELCOME_SUCCESS';
export const LOGIN_TRUE = 'LOGIN_TRUE';
export const LOGIN_FALSE = 'LOGIN_FALSE';
